"""empty message

Revision ID: 030409210205
Revises: 1ffe25af2a02
Create Date: 2021-09-11 17:31:40.835907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030409210205'
down_revision = '1ffe25af2a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('system', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('is_mobile', sa.Boolean(), nullable=True),
    sa.Column('device_uuid', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_log')
    # ### end Alembic commands ###
