"""empty message

Revision ID: 03a60879b283
Revises: ffc79d0f2350
Create Date: 2021-09-12 00:01:11.678446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a60879b283'
down_revision = 'ffc79d0f2350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_log', sa.Column('country_code', sa.String(length=10), nullable=True))
    op.add_column('request_log', sa.Column('country_name', sa.String(length=10), nullable=True))
    op.add_column('request_log', sa.Column('city', sa.String(length=10), nullable=True))
    op.add_column('request_log', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('request_log', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_log', 'longitude')
    op.drop_column('request_log', 'latitude')
    op.drop_column('request_log', 'city')
    op.drop_column('request_log', 'country_name')
    op.drop_column('request_log', 'country_code')
    # ### end Alembic commands ###
