"""empty message

Revision ID: 0ba0d491af48
Revises: 03a60879b283
Create Date: 2021-09-12 00:24:18.119630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ba0d491af48'
down_revision = '03a60879b283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_log', 'end_time')
    op.drop_column('request_log', 'url')
    op.drop_column('request_log', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_log', sa.Column('start_time', mysql.DATETIME(), nullable=False))
    op.add_column('request_log', sa.Column('url', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('request_log', sa.Column('end_time', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
