"""add_website_and_desc

Revision ID: 1142f9eb67c0
Revises: c9cc977cbf56
Create Date: 2020-12-20 12:21:58.069338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1142f9eb67c0'
down_revision = 'c9cc977cbf56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('user_desc', sa.Text(), nullable=True, comment='使用说明'))
    op.add_column('membership', sa.Column('website', sa.String(length=50), nullable=True, comment='网站'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membership', 'website')
    op.drop_column('membership', 'user_desc')
    # ### end Alembic commands ###
