"""empty message

Revision ID: 19b48cdd3f85
Revises: 0ba0d491af48
Create Date: 2021-09-12 00:25:46.982627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b48cdd3f85'
down_revision = '0ba0d491af48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_log', sa.Column('order_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_log', 'order_id')
    # ### end Alembic commands ###
