"""change_membership_schema

Revision ID: 3dcce1578e20
Revises: aae6deb3f213
Create Date: 2020-12-20 11:52:14.874854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3dcce1578e20'
down_revision = 'aae6deb3f213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('account', sa.String(length=50), nullable=True, comment='账号'))
    op.add_column('membership', sa.Column('membership_type', sa.Integer(), nullable=True, comment='会员类型'))
    op.drop_column('membership', 'username')
    op.drop_column('membership', 'uuid')
    op.drop_column('membership', 'member_type')
    op.drop_column('membership', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='时长'))
    op.add_column('membership', sa.Column('member_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='会员类型'))
    op.add_column('membership', sa.Column('uuid', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('membership', sa.Column('username', mysql.VARCHAR(length=50), nullable=True, comment='用户名'))
    op.drop_column('membership', 'membership_type')
    op.drop_column('membership', 'account')
    # ### end Alembic commands ###
