"""empty message

Revision ID: 7533ffd97bc9
Revises: 030409210205
Create Date: 2021-09-11 20:24:48.322323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7533ffd97bc9'
down_revision = '030409210205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('pwd', sa.String(length=50), nullable=True, comment='邮箱密码'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membership', 'pwd')
    # ### end Alembic commands ###
