"""init_schema

Revision ID: aae6deb3f213
Revises: 
Create Date: 2020-12-20 11:46:04.690023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae6deb3f213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership',
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id主键'),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True, comment='会员名称'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='时长'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=50), nullable=True, comment='密码'),
    sa.Column('member_type', sa.Integer(), nullable=True, comment='会员类型'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcome',
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id主键'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金额'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='支出名称'),
    sa.Column('catalog', sa.String(length=50), nullable=True, comment='支出分类'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id主键'),
    sa.Column('username', sa.String(length=20), nullable=True, comment='username'),
    sa.Column('first_name', sa.String(length=20), nullable=True, comment='first_name'),
    sa.Column('last_name', sa.String(length=20), nullable=True, comment='last_name'),
    sa.Column('email', sa.String(length=20), nullable=True, comment='email'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('outcome')
    op.drop_table('membership')
    # ### end Alembic commands ###
