"""empty message

Revision ID: cd8ed1652710
Revises: 19b48cdd3f85
Create Date: 2021-09-12 00:27:33.843121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd8ed1652710'
down_revision = '19b48cdd3f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_log', 'params')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_log', sa.Column('params', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
